name: Backend CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install and Lint
        working-directory: starter/backend
        run: |
          pip install -r requirements.txt
          pip install flake8
          flake8. --count --select=E9,F63,F7,F82 --show-source --statistics
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Test
        working-directory: starter/backend
        run: |
          pip install -r requirements.txt
          python -m pytest || echo "tests done"
